export const data = [
  {
    image: require("./Assests/image12.png"),
    rate: 5.0,
    pepole: 6,
    country: "USA",
    desc: "Life lessons with Katie Zaferes",
    price: 120,
    avaliable: 0,
    onOf: "online",
  },
  {
    image: require("./Assests/wedding-photography1.png"),
    rate: 5.0,
    pepole: 30,
    country: "USA",
    desc: "Learn wedding photography",
    price: 250,
    avaliable: 25,
    onOf: "face",
  },
  {
    image: require("./Assests/mountain-bike1.png"),
    rate: 4.8,
    pepole: 6,
    country: "USA",
    desc: "Group Mountain Biking",
    price: 125,
    onOf: "face",
  },
];
